COUNTRY_CODES = [
    {"name": "Afghanistan", "iso": "AF", "dial_code": "+93"},
    {"name": "Albania", "iso": "AL", "dial_code": "+355"},
    {"name": "Algeria", "iso": "DZ", "dial_code": "+213"},
    {"name": "American Samoa", "iso": "AS", "dial_code": "+1684"},
    {"name": "Andorra", "iso": "AD", "dial_code": "+376"},
    {"name": "Angola", "iso": "AO", "dial_code": "+244"},
    {"name": "Anguilla", "iso": "AI", "dial_code": "+1264"},
    {"name": "Antigua and Barbuda", "iso": "AG", "dial_code": "+1268"},
    {"name": "Argentina", "iso": "AR", "dial_code": "+54"},
    {"name": "Armenia", "iso": "AM", "dial_code": "+374"},
    {"name": "Aruba", "iso": "AW", "dial_code": "+297"},
    {"name": "Australia", "iso": "AU", "dial_code": "+61"},
    {"name": "Austria", "iso": "AT", "dial_code": "+43"},
    {"name": "Azerbaijan", "iso": "AZ", "dial_code": "+994"},
    {"name": "Bahamas", "iso": "BS", "dial_code": "+1242"},
    {"name": "Bahrain", "iso": "BH", "dial_code": "+973"},
    {"name": "Bangladesh", "iso": "BD", "dial_code": "+880"},
    {"name": "Barbados", "iso": "BB", "dial_code": "+1246"},
    {"name": "Belarus", "iso": "BY", "dial_code": "+375"},
    {"name": "Belgium", "iso": "BE", "dial_code": "+32"},
    {"name": "Belize", "iso": "BZ", "dial_code": "+501"},
    {"name": "Benin", "iso": "BJ", "dial_code": "+229"},
    {"name": "Bermuda", "iso": "BM", "dial_code": "+1441"},
    {"name": "Bhutan", "iso": "BT", "dial_code": "+975"},
    {"name": "Bolivia", "iso": "BO", "dial_code": "+591"},
    {"name": "Bosnia and Herzegovina", "iso": "BA", "dial_code": "+387"},
    {"name": "Botswana", "iso": "BW", "dial_code": "+267"},
    {"name": "Brazil", "iso": "BR", "dial_code": "+55"},
    {"name": "British Indian Ocean Territory", "iso": "IO", "dial_code": "+246"},
    {"name": "British Virgin Islands", "iso": "VG", "dial_code": "+1284"},
    {"name": "Brunei", "iso": "BN", "dial_code": "+673"},
    {"name": "Bulgaria", "iso": "BG", "dial_code": "+359"},
    {"name": "Burkina Faso", "iso": "BF", "dial_code": "+226"},
    {"name": "Burundi", "iso": "BI", "dial_code": "+257"},
    {"name": "Cambodia", "iso": "KH", "dial_code": "+855"},
    {"name": "Cameroon", "iso": "CM", "dial_code": "+237"},
    {"name": "Canada", "iso": "CA", "dial_code": "+1"},
    {"name": "Cape Verde", "iso": "CV", "dial_code": "+238"},
    {"name": "Cayman Islands", "iso": "KY", "dial_code": "+1345"},
    {"name": "Central African Republic", "iso": "CF", "dial_code": "+236"},
    {"name": "Chad", "iso": "TD", "dial_code": "+235"},
    {"name": "Chile", "iso": "CL", "dial_code": "+56"},
    {"name": "China", "iso": "CN", "dial_code": "+86"},
    {"name": "Christmas Island", "iso": "CX", "dial_code": "+61"},
    {"name": "Cocos Islands", "iso": "CC", "dial_code": "+61"},
    {"name": "Colombia", "iso": "CO", "dial_code": "+57"},
    {"name": "Comoros", "iso": "KM", "dial_code": "+269"},
    {"name": "Cook Islands", "iso": "CK", "dial_code": "+682"},
    {"name": "Costa Rica", "iso": "CR", "dial_code": "+506"},
    {"name": "Croatia", "iso": "HR", "dial_code": "+385"},
    {"name": "Cuba", "iso": "CU", "dial_code": "+53"},
    {"name": "Curacao", "iso": "CW", "dial_code": "+599"},
    {"name": "Cyprus", "iso": "CY", "dial_code": "+357"},
    {"name": "Czech Republic", "iso": "CZ", "dial_code": "+420"},
    {"name": "Democratic Republic of the Congo", "iso": "CD", "dial_code": "+243"},
    {"name": "Denmark", "iso": "DK", "dial_code": "+45"},
    {"name": "Djibouti", "iso": "DJ", "dial_code": "+253"},
    {"name": "Dominica", "iso": "DM", "dial_code": "+1767"},
    {"name": "Dominican Republic", "iso": "DO", "dial_code": "+1809"},
    {"name": "East Timor", "iso": "TL", "dial_code": "+670"},
    {"name": "Ecuador", "iso": "EC", "dial_code": "+593"},
    {"name": "Egypt", "iso": "EG", "dial_code": "+20"},
    {"name": "El Salvador", "iso": "SV", "dial_code": "+503"},
    {"name": "Equatorial Guinea", "iso": "GQ", "dial_code": "+240"},
    {"name": "Eritrea", "iso": "ER", "dial_code": "+291"},
    {"name": "Estonia", "iso": "EE", "dial_code": "+372"},
    {"name": "Eswatini", "iso": "SZ", "dial_code": "+268"},
    {"name": "Ethiopia", "iso": "ET", "dial_code": "+251"},
    {"name": "Falkland Islands", "iso": "FK", "dial_code": "+500"},
    {"name": "Faroe Islands", "iso": "FO", "dial_code": "+298"},
    {"name": "Fiji", "iso": "FJ", "dial_code": "+679"},
    {"name": "Finland", "iso": "FI", "dial_code": "+358"},
    {"name": "France", "iso": "FR", "dial_code": "+33"},
    {"name": "French Polynesia", "iso": "PF", "dial_code": "+689"},
    {"name": "Gabon", "iso": "GA", "dial_code": "+241"},
    {"name": "Gambia", "iso": "GM", "dial_code": "+220"},
    {"name": "Georgia", "iso": "GE", "dial_code": "+995"},
    {"name": "Germany", "iso": "DE", "dial_code": "+49"},
    {"name": "Ghana", "iso": "GH", "dial_code": "+233"},
    {"name": "Gibraltar", "iso": "GI", "dial_code": "+350"},
    {"name": "Greece", "iso": "GR", "dial_code": "+30"},
    {"name": "Greenland", "iso": "GL", "dial_code": "+299"},
    {"name": "Grenada", "iso": "GD", "dial_code": "+1473"},
    {"name": "Guam", "iso": "GU", "dial_code": "+1671"},
    {"name": "Guatemala", "iso": "GT", "dial_code": "+502"},
    {"name": "Guernsey", "iso": "GG", "dial_code": "+44"},
    {"name": "Guinea", "iso": "GN", "dial_code": "+224"},
    {"name": "Guinea-Bissau", "iso": "GW", "dial_code": "+245"},
    {"name": "Guyana", "iso": "GY", "dial_code": "+592"},
    {"name": "Haiti", "iso": "HT", "dial_code": "+509"},
    {"name": "Honduras", "iso": "HN", "dial_code": "+504"},
    {"name": "Hong Kong", "iso": "HK", "dial_code": "+852"},
    {"name": "Hungary", "iso": "HU", "dial_code": "+36"},
    {"name": "Iceland", "iso": "IS", "dial_code": "+354"},
    {"name": "India", "iso": "IN", "dial_code": "+91"},
    {"name": "Indonesia", "iso": "ID", "dial_code": "+62"},
    {"name": "Iran", "iso": "IR", "dial_code": "+98"},
    {"name": "Iraq", "iso": "IQ", "dial_code": "+964"},
    {"name": "Ireland", "iso": "IE", "dial_code": "+353"},
    {"name": "Isle of Man", "iso": "IM", "dial_code": "+44"},
    {"name": "Israel", "iso": "IL", "dial_code": "+972"},
    {"name": "Italy", "iso": "IT", "dial_code": "+39"},
    {"name": "Ivory Coast", "iso": "CI", "dial_code": "+225"},
    {"name": "Jamaica", "iso": "JM", "dial_code": "+1876"},
    {"name": "Japan", "iso": "JP", "dial_code": "+81"},
    {"name": "Jersey", "iso": "JE", "dial_code": "+44"},
    {"name": "Jordan", "iso": "JO", "dial_code": "+962"},
    {"name": "Kazakhstan", "iso": "KZ", "dial_code": "+7"},
    {"name": "Kenya", "iso": "KE", "dial_code": "+254"},
    {"name": "Kiribati", "iso": "KI", "dial_code": "+686"},
    {"name": "Kosovo", "iso": "XK", "dial_code": "+383"},
    {"name": "Kuwait", "iso": "KW", "dial_code": "+965"},
    {"name": "Kyrgyzstan", "iso": "KG", "dial_code": "+996"},
    {"name": "Laos", "iso": "LA", "dial_code": "+856"},
    {"name": "Latvia", "iso": "LV", "dial_code": "+371"},
    {"name": "Lebanon", "iso": "LB", "dial_code": "+961"},
    {"name": "Lesotho", "iso": "LS", "dial_code": "+266"},
    {"name": "Liberia", "iso": "LR", "dial_code": "+231"},
    {"name": "Libya", "iso": "LY", "dial_code": "+218"},
    {"name": "Liechtenstein", "iso": "LI", "dial_code": "+423"},
    {"name": "Lithuania", "iso": "LT", "dial_code": "+370"},
    {"name": "Luxembourg", "iso": "LU", "dial_code": "+352"},
    {"name": "Macau", "iso": "MO", "dial_code": "+853"},
    {"name": "North Macedonia", "iso": "MK", "dial_code": "+389"},
    {"name": "Madagascar", "iso": "MG", "dial_code": "+261"},
    {"name": "Malawi", "iso": "MW", "dial_code": "+265"},
    {"name": "Malaysia", "iso": "MY", "dial_code": "+60"},
    {"name": "Maldives", "iso": "MV", "dial_code": "+960"},
    {"name": "Mali", "iso": "ML", "dial_code": "+223"},
    {"name": "Malta", "iso": "MT", "dial_code": "+356"},
    {"name": "Marshall Islands", "iso": "MH", "dial_code": "+692"},
    {"name": "Mauritania", "iso": "MR", "dial_code": "+222"},
    {"name": "Mauritius", "iso": "MU", "dial_code": "+230"},
    {"name": "Mayotte", "iso": "YT", "dial_code": "+262"},
    {"name": "Mexico", "iso": "MX", "dial_code": "+52"},
    {"name": "Micronesia", "iso": "FM", "dial_code": "+691"},
    {"name": "Moldova", "iso": "MD", "dial_code": "+373"},
    {"name": "Monaco", "iso": "MC", "dial_code": "+377"},
    {"name": "Mongolia", "iso": "MN", "dial_code": "+976"},
    {"name": "Montenegro", "iso": "ME", "dial_code": "+382"},
    {"name": "Montserrat", "iso": "MS", "dial_code": "+1664"},
    {"name": "Morocco", "iso": "MA", "dial_code": "+212"},
    {"name": "Mozambique", "iso": "MZ", "dial_code": "+258"},
    {"name": "Myanmar", "iso": "MM", "dial_code": "+95"},
    {"name": "Namibia", "iso": "NA", "dial_code": "+264"},
    {"name": "Nauru", "iso": "NR", "dial_code": "+674"},
    {"name": "Nepal", "iso": "NP", "dial_code": "+977"},
    {"name": "Netherlands", "iso": "NL", "dial_code": "+31"},
    {"name": "New Caledonia", "iso": "NC", "dial_code": "+687"},
    {"name": "New Zealand", "iso": "NZ", "dial_code": "+64"},
    {"name": "Nicaragua", "iso": "NI", "dial_code": "+505"},
    {"name": "Niger", "iso": "NE", "dial_code": "+227"},
    {"name": "Nigeria", "iso": "NG", "dial_code": "+234"},
    {"name": "Niue", "iso": "NU", "dial_code": "+683"},
    {"name": "North Korea", "iso": "KP", "dial_code": "+850"},
    {"name": "Northern Mariana Islands", "iso": "MP", "dial_code": "+1670"},
    {"name": "Norway", "iso": "NO", "dial_code": "+47"},
    {"name": "Oman", "iso": "OM", "dial_code": "+968"},
    {"name": "Pakistan", "iso": "PK", "dial_code": "+92"},
    {"name": "Palau", "iso": "PW", "dial_code": "+680"},
    {"name": "Palestine", "iso": "PS", "dial_code": "+970"},
    {"name": "Panama", "iso": "PA", "dial_code": "+507"},
    {"name": "Papua New Guinea", "iso": "PG", "dial_code": "+675"},
    {"name": "Paraguay", "iso": "PY", "dial_code": "+595"},
    {"name": "Peru", "iso": "PE", "dial_code": "+51"},
    {"name": "Philippines", "iso": "PH", "dial_code": "+63"},
    {"name": "Pitcairn Islands", "iso": "PN", "dial_code": "+64"},
    {"name": "Poland", "iso": "PL", "dial_code": "+48"},
    {"name": "Portugal", "iso": "PT", "dial_code": "+351"},
    {"name": "Puerto Rico", "iso": "PR", "dial_code": "+1787"},
    {"name": "Qatar", "iso": "QA", "dial_code": "+974"},
    {"name": "Republic of the Congo", "iso": "CG", "dial_code": "+242"},
    {"name": "Reunion", "iso": "RE", "dial_code": "+262"},
    {"name": "Romania", "iso": "RO", "dial_code": "+40"},
    {"name": "Russia", "iso": "RU", "dial_code": "+7"},
    {"name": "Rwanda", "iso": "RW", "dial_code": "+250"},
    {"name": "Saint Barthelemy", "iso": "BL", "dial_code": "+590"},
    {"name": "Saint Helena", "iso": "SH", "dial_code": "+290"},
    {"name": "Saint Kitts and Nevis", "iso": "KN", "dial_code": "+1869"},
    {"name": "Saint Lucia", "iso": "LC", "dial_code": "+1758"},
    {"name": "Saint Martin", "iso": "MF", "dial_code": "+590"},
    {"name": "Saint Pierre and Miquelon", "iso": "PM", "dial_code": "+508"},
    {"name": "Saint Vincent and the Grenadines", "iso": "VC", "dial_code": "+1784"},
    {"name": "Samoa", "iso": "WS", "dial_code": "+685"},
    {"name": "San Marino", "iso": "SM", "dial_code": "+378"},
    {"name": "Sao Tome and Principe", "iso": "ST", "dial_code": "+239"},
    {"name": "Saudi Arabia", "iso": "SA", "dial_code": "+966"},
    {"name": "Senegal", "iso": "SN", "dial_code": "+221"},
    {"name": "Serbia", "iso": "RS", "dial_code": "+381"},
    {"name": "Seychelles", "iso": "SC", "dial_code": "+248"},
    {"name": "Sierra Leone", "iso": "SL", "dial_code": "+232"},
    {"name": "Singapore", "iso": "SG", "dial_code": "+65"},
    {"name": "Sint Maarten", "iso": "SX", "dial_code": "+1721"},
    {"name": "Slovakia", "iso": "SK", "dial_code": "+421"},
    {"name": "Slovenia", "iso": "SI", "dial_code": "+386"},
    {"name": "Solomon Islands", "iso": "SB", "dial_code": "+677"},
    {"name": "Somalia", "iso": "SO", "dial_code": "+252"},
    {"name": "South Africa", "iso": "ZA", "dial_code": "+27"},
    {"name": "South Korea", "iso": "KR", "dial_code": "+82"},
    {"name": "South Sudan", "iso": "SS", "dial_code": "+211"},
    {"name": "Spain", "iso": "ES", "dial_code": "+34"},
    {"name": "Sri Lanka", "iso": "LK", "dial_code": "+94"},
    {"name": "Sudan", "iso": "SD", "dial_code": "+249"},
    {"name": "Suriname", "iso": "SR", "dial_code": "+597"},
    {"name": "Svalbard and Jan Mayen", "iso": "SJ", "dial_code": "+47"},
    {"name": "Sweden", "iso": "SE", "dial_code": "+46"},
    {"name": "Switzerland", "iso": "CH", "dial_code": "+41"},
    {"name": "Syria", "iso": "SY", "dial_code": "+963"},
    {"name": "Taiwan", "iso": "TW", "dial_code": "+886"},
    {"name": "Tajikistan", "iso": "TJ", "dial_code": "+992"},
    {"name": "Tanzania", "iso": "TZ", "dial_code": "+255"},
    {"name": "Thailand", "iso": "TH", "dial_code": "+66"},
    {"name": "Togo", "iso": "TG", "dial_code": "+228"},
    {"name": "Tokelau", "iso": "TK", "dial_code": "+690"},
    {"name": "Tonga", "iso": "TO", "dial_code": "+676"},
    {"name": "Trinidad and Tobago", "iso": "TT", "dial_code": "+1868"},
    {"name": "Tunisia", "iso": "TN", "dial_code": "+216"},
    {"name": "Turkey", "iso": "TR", "dial_code": "+90"},
    {"name": "Turkmenistan", "iso": "TM", "dial_code": "+993"},
    {"name": "Turks and Caicos Islands", "iso": "TC", "dial_code": "+1649"},
    {"name": "Tuvalu", "iso": "TV", "dial_code": "+688"},
    {"name": "U.S. Virgin Islands", "iso": "VI", "dial_code": "+1340"},
    {"name": "Uganda", "iso": "UG", "dial_code": "+256"},
    {"name": "Ukraine", "iso": "UA", "dial_code": "+380"},
    {"name": "United Arab Emirates", "iso": "AE", "dial_code": "+971"},
    {"name": "United Kingdom", "iso": "GB", "dial_code": "+44"},
    {"name": "United States", "iso": "US", "dial_code": "+1"},
    {"name": "Uruguay", "iso": "UY", "dial_code": "+598"},
    {"name": "Uzbekistan", "iso": "UZ", "dial_code": "+998"},
    {"name": "Vanuatu", "iso": "VU", "dial_code": "+678"},
    {"name": "Vatican City", "iso": "VA", "dial_code": "+379"},
    {"name": "Venezuela", "iso": "VE", "dial_code": "+58"},
    {"name": "Vietnam", "iso": "VN", "dial_code": "+84"},
    {"name": "Wallis and Futuna", "iso": "WF", "dial_code": "+681"},
    {"name": "Western Sahara", "iso": "EH", "dial_code": "+212"},
    {"name": "Yemen", "iso": "YE", "dial_code": "+967"},
    {"name": "Zambia", "iso": "ZM", "dial_code": "+260"},
    {"name": "Zimbabwe", "iso": "ZW", "dial_code": "+263"},
]

DIAL_CODES = {entry["dial_code"] for entry in COUNTRY_CODES}
